import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainSidebar from "@/components/AdminSidebar/MainSidebar";
import { Sidebar } from "@/components/Sidebar/sidebar";
import Header from "@/components/Header/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex items-center h-screen">
          <Header />
          <Sidebar isSideBarOpen={true} setSideBarOpen={() => {}}>
            <MainSidebar />
          </Sidebar>
        </div>
        {children}
      </body>
    </html>
  );
}
